---
# Install Postgres DB for Trading application
# Needs be to installed "geerlingguy.postgresql" role from Ansible Galaxy
- name: Install sever with traiding app
  hosts: db-servers
  become: yes
  vars_files:
    - vars/db-postgresql.yaml
    - vars/common.yaml

  pre_tasks:
  - name: Install common admin user - "{{ admin_user }}"
    user:
      name: "{{ admin_user }}"
      shell: /bin/bash
      state: present
      createhome: yes

  - name: Configure sudoers file for admin account
    template:
      src:  files/sudoers.jp2
      dest: /etc/sudoers.d/{{ admin_user }}

  - name: Copy SSH public keys
    authorized_key:
      manage_dir: yes
      key:  "{{ lookup('file', 'files/ssh_keys.pub') }}"
      user: "{{ admin_user }}"

  - name: Install system yum packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - epel-release
      - vim
      - nano
      - curl
      - tmux

  roles:
    - geerlingguy.postgresql