---
# Install server for Trading application
# 
- name: Install sever with traiding app
  hosts: app-servers
  become: yes
  vars:
    services_list:
      - manager
      - frontend
      - logic
      - query
    admin_user: "centos"

  tasks:
  - name: Install common admin user - "{{ admin_user }}"
    user:
      name: "{{ admin_user }}"
      shell: /bin/bash
      state: present
      createhome: yes

  - name: Configure sudoers file for admin account
    template:
      src:  files/sudoers.jp2
      dest: /etc/sudoers.d/{{ admin_user }}

  - name: Copy SSH public keys
    authorized_key:
      manage_dir: yes
      key:  "{{ lookup('file', 'files/ssh_keys.pub') }}"
      user: "{{ admin_user }}"

  - name: Install system yum packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - epel-release
      - vim
      - nano
      - curl 
      - tmux
      - git
      - python-setuptools
      - python36 
      - python36-pip
   
  - name: Update pip3
    pip: 
      name: pip
      state: latest
      executable: pip3
      extra_args: --install-option="--prefix=/usr/"

  - name: Install pip3 packages
    pip:
      name: "{{ item }}"
      executable: pip3
    with_items:
      - Flask
      - PyYAML
      - requests

  - name: Create system users for running applications
    user:
      name: "app-{{ item }}"
      system: "yes"
      shell: "/usr/bin/false"
      create_home: "no"
    with_items:
      - "{{ services_list }}"

  - name: Create directories for applications
    file: 
      path: "/opt/app-{{ item }}"
      state: directory
      mode: '0755'
      owner: "app-{{ item }}"
      group: "app-{{ item }}"
    with_items:
      - "{{ services_list }}"

#  - name: Install applications
